<?php
return array(
	//'配置项'=>'配置值'
    'DB_PREFIX'	=> 'bmp_',
    'DB_DEBUG'  		=>  true,
    'LOG_RECORD' => true, // 开启日志记录
    'platformId'=> 'A00002016120000000294',
    'operId'=>'10010A0001',
    'dataSrc'=>'2',
    'BASE64P12DATA' => 'MIIDfgIBATBHBgoqgRzPVQYBBAIBBgcqgRzPVQFoBDClyXV+hNlZh3J71DfGgmQuXE/Meyqo68/FIk7Zb+vaJhsa7RCwhkA5Xn/IRezDQ7AwggMuBgoqgRzPVQYBBAIBBIIDHjCCAxowggK9oAMCAQICBTABAnBYMAwGCCqBHM9VAYN1BQAwKzELMAkGA1UEBhMCQ04xHDAaBgNVBAoME0NGQ0EgU00yIFRFU1QgT0NBMjEwHhcNMTUwMzA2MDMwMzMyWhcNMTYwMzA2MDMwMzMyWjB0MQswCQYDVQQGEwJDTjENMAsGA1UECgwEQ01CQzESMBAGA1UECwwJQ01CQ19EQ01TMRUwEwYDVQQLDAxJbmRpdmlkdWFsLTExKzApBgNVBAMMIjAzMDVAMDk1MDA1ODAwNjcxNjEzMUB1c2VyNTQ5NTM3QDEwWTATBgcqhkjOPQIBBggqgRzPVQGCLQNCAATHK/KpRVf8e4pUFs2ov+hAjgoasBbxSi4yhEP3u0h9xlDaTw4fZyKExwbmADS+NXythbCpkIP/clhcibf3x2m2o4IBgTCCAX0wHwYDVR0jBBgwFoAU4n62ELuU6xXmrtEVCv/o16BXOZ0wSAYDVR0gBEEwPzA9BghggRyG7yoCAjAxMC8GCCsGAQUFBwIBFiNodHRwOi8vd3d3LmNmY2EuY29tLmNuL3VzL3VzLTEzLmh0bTCBzgYDVR0fBIHGMIHDMIGSoIGPoIGMhoGJbGRhcDovLzIxMC43NC40Mi4xMDozODkvY249Y3JsMjUsT1U9U00yLE9VPUNSTCxPPUNGQ0EgU00yIFRFU1QgT0NBMjEsQz1DTj9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Y2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnQwLKAqoCiGJmh0dHA6Ly8yMTAuNzQuNDIuMy9PQ0EyMS9TTTIvY3JsMjUuY3JsMAsGA1UdDwQEAwID6DAdBgNVHQ4EFgQUWZTc4hyNnBa1uRKdcptd3JDjKBkwEwYDVR0lBAwwCgYIKwYBBQUHAwIwDAYIKoEcz1UBg3UFAANJADBGAiEAsKWbuI3Kd4sujhzRXwbesYKjT74vIFYMrvLLDVYe2YQCIQC/RjQoNpJXclt+xbUSpqYuK1rC7LEKxEN1YanXJ3SxMg==',
    //私钥密码
    'P12PASSWORD'=>'123123',
    //民生公钥
    'BASE64X509CERTDATA' => 'MIIDGjCCAr2gAwIBAgIFMAE1UAQwDAYIKoEcz1UBg3UFADArMQswCQYDVQQGEwJDTjEcMBoGA1UECgwTQ0ZDQSBTTTIgVEVTVCBPQ0EyMTAeFw0xNTEyMDQwODU4MDlaFw0xNjEyMDQwODU4MDlaMHQxCzAJBgNVBAYTAkNOMQ0wCwYDVQQKDARDTUJDMRIwEAYDVQQLDAlDTUJDX0RDTVMxFTATBgNVBAsMDEluZGl2aWR1YWwtMTErMCkGA1UEAwwiMDMwNUAwMzE4NzQ0ODYyNzc5ODM3QHVzZXIwMDMyNDRAMTBZMBMGByqGSM49AgEGCCqBHM9VAYItA0IABMaqALdw4tIJEcYg2Bv6TMNj8Odv9cmK5+QVnrjjwxnLMOoXuzn17R0E7YBAe7j87Krhxqstx6qLcuvGh2jJGUOjggGBMIIBfTAfBgNVHSMEGDAWgBTifrYQu5TrFeau0RUK/+jXoFc5nTBIBgNVHSAEQTA/MD0GCGCBHIbvKgICMDEwLwYIKwYBBQUHAgEWI2h0dHA6Ly93d3cuY2ZjYS5jb20uY24vdXMvdXMtMTMuaHRtMIHOBgNVHR8EgcYwgcMwgZKggY+ggYyGgYlsZGFwOi8vMjEwLjc0LjQyLjEwOjM4OS9jbj1jcmw5NSxvdT1TTTIsT1U9Q1JMLE89Q0ZDQSBTTTIgVEVTVCBPQ0EyMSxDPUNOP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RjbGFzcz1jUkxEaXN0cmlidXRpb25Qb2ludDAsoCqgKIYmaHR0cDovLzIxMC43NC40Mi4zL09DQTIxL1NNMi9jcmw5NS5jcmwwCwYDVR0PBAQDAgPoMB0GA1UdDgQWBBS1x/e/puEJbLQnTtwm2y/+fP1b2jATBgNVHSUEDDAKBggrBgEFBQcDAjAMBggqgRzPVQGDdQUAA0kAMEYCIQCba06exmipgEcbA1uhsM19ldoVY6QDlIqx1+8fjy7xAgIhALboidd/NmhTdWKgbs8FRyaYuEbHuu6BNWYeC46GWzTD',
    'SIGNALG1' => 'SM3withSM2',//加密方式1，用于签名和校验签名
    'SIGNALG2' => 'SM4/CBC/PKCS7Padding',//加密方式2，用于加密信封和解密信封'
    'REG_STORE_URL' => "http://wxpay.cmbc.com.cn/mobilePlatform/lcbpService/mchntAdd.do",
    'MOD_STORE_URL' => "http://wxpay.cmbc.com.cn/mobilePlatform/lcbpService/mchntUpd.do",
    'BIND_PAY_URL' =>"http://wxpay.cmbc.com.cn/mobilePlatform/lcbpService/chnlAdd.do",
    'MOD_PAY_URL' => "http://wxpay.cmbc.com.cn/mobilePlatform/lcbpService/chnlUpd.do",

    'PAY_URL' => "http://wxpay.cmbc.com.cn/mobilePlatform/appserver/lcbpPay.do",
    'NOTIFY_URL' => "http://wxpay.cmbc.com.cn/cmbcpaydemo/NoticeServlet?name=notice",
    'QUERY_TRANSACTION_URL' => 'http://wxpay.cmbc.com.cn/mobilePlatform/appserver/paymentResultSelect.do',
);